# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adc_dma_test_pinout.xdc

# Block Designs: bd/adc_dma_bd/adc_dma_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd || ORIG_REF_NAME==adc_dma_bd} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_processing_system7_0_0/adc_dma_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_processing_system7_0_0 || ORIG_REF_NAME==adc_dma_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_axi_dma_0_0/adc_dma_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_axi_dma_0_0 || ORIG_REF_NAME==adc_dma_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_ZmodADC1410_Controll_0_0/adc_dma_bd_ZmodADC1410_Controll_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_ZmodADC1410_Controll_0_0 || ORIG_REF_NAME==adc_dma_bd_ZmodADC1410_Controll_0_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_xbar_0/adc_dma_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_xbar_0 || ORIG_REF_NAME==adc_dma_bd_xbar_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_auto_pc_0/adc_dma_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_auto_pc_0 || ORIG_REF_NAME==adc_dma_bd_auto_pc_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_auto_cc_0/adc_dma_bd_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_auto_cc_0 || ORIG_REF_NAME==adc_dma_bd_auto_cc_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_ps7_0_axi_periph_0/adc_dma_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==adc_dma_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_rst_ps7_0_100M_0/adc_dma_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==adc_dma_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_xbar_1/adc_dma_bd_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_xbar_1 || ORIG_REF_NAME==adc_dma_bd_xbar_1} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_auto_us_0/adc_dma_bd_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_auto_us_0 || ORIG_REF_NAME==adc_dma_bd_auto_us_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_auto_us_1/adc_dma_bd_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_auto_us_1 || ORIG_REF_NAME==adc_dma_bd_auto_us_1} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_auto_pc_1/adc_dma_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_auto_pc_1 || ORIG_REF_NAME==adc_dma_bd_auto_pc_1} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_axi_mem_intercon_0/adc_dma_bd_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_axi_mem_intercon_0 || ORIG_REF_NAME==adc_dma_bd_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_xlconcat_0_0/adc_dma_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_xlconcat_0_0 || ORIG_REF_NAME==adc_dma_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_clk_wiz_0_0/adc_dma_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_clk_wiz_0_0 || ORIG_REF_NAME==adc_dma_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_AXI_ZmodADC1410_0_0/adc_dma_bd_AXI_ZmodADC1410_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_AXI_ZmodADC1410_0_0 || ORIG_REF_NAME==adc_dma_bd_AXI_ZmodADC1410_0_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_rst_ps7_0_100M_1_0/adc_dma_bd_rst_ps7_0_100M_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_rst_ps7_0_100M_1_0 || ORIG_REF_NAME==adc_dma_bd_rst_ps7_0_100M_1_0} -quiet] -quiet

# IP: bd/adc_dma_bd/ip/adc_dma_bd_AXI_TAR_0_0/adc_dma_bd_AXI_TAR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc_dma_bd_AXI_TAR_0_0 || ORIG_REF_NAME==adc_dma_bd_AXI_TAR_0_0} -quiet] -quiet

# XDC: /home/sebas/Escritorio/proyecto/workspace/adc_dma_test/adc_dma_test.gen/sources_1/bd/adc_dma_bd/adc_dma_bd_ooc.xdc
